<div class="tw-smartfeed-password">
    <div class="tw-smartfeed-title">
        <?php echo $this->__('Forgot your password?'); ?>
    </div>

    <div id="tw-smartfeed-content">
        <div id="close">
            <img src="<?php echo $this->getSkinUrl('twenga_smartfeed/images/window_close.png'); ?>" title="<?php echo $this->__('Close'); ?>" alt="<?php echo $this->__('Close'); ?>" />
        </div>
        <div id="ajaxerror"></div>
        <div id="ajaxsuccess"></div>
        <form id="lost_password" action="" method="POST">
            <?php echo $this->getBlockHtml('formkey')?>

            <div class="field">
                <label for="email"><?php echo $this->__('Please enter your email address:'); ?></label>
                <input id="email" type="text" name="email" class="validate-email required-entry" />
            </div>

            <div class="button-wrap">
                <div class="row">
                    <div class="col-sm-5 col-sm-offset-3">
                        <a href="#" class="btn btn-red btn-lg" onclick="sendRequest();"><?php echo $this->__('Submit'); ?></a>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

<script type="text/javascript">
    //<![CDATA[
    function sendRequest() {
        var email = document.getElementById('email').value;
        var form_key = '<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>';
        var req = new Ajax.Request('<?php echo Mage::helper("adminhtml")->getUrl('adminhtml/smartfeed_index/postlostpassword'); ?>', {
            method:'post',
            parameters: {
                email: email,
                form_key: form_key
            },
            onSuccess: function(req, json){
                eval('var json = ' + req.responseText);
                if (json.error == true) {
                    document.getElementById('ajaxerror').innerHTML = json.error_message;
                    document.getElementById('ajaxsuccess').innerHTML = '';
                }

                if (json.success == true) {
                    document.getElementById('ajaxerror').innerHTML = '';
                    document.getElementById('ajaxsuccess').innerHTML = json.success_message;
                }
            }
        });
    }
    //]]>
</script>
